export const statesColors =[{
    "id": "US.NY",
    "name": "New York",
    "value": "10"
}, {
    "id": "US.CA",
    "name": "California",
    "value": "6"
}, {
    "id": "US.GA",
    "name": "Georgia",
    "value": "6"
}, {
    "id": "US.FL",
    "name": "Florida",
    "value": "5"
}, {
    "id": "US.NJ",
    "name": "New Jersey",
    "value": "5"
}, {
    "id": "US.AR",
    "name": "Arkansas",
    "value": "4"
}, {
    "id": "US.ME",
    "name": "Maine",
    "value": "4"
}, {
    "id": "US.AZ",
    "name": "Arizona",
    "value": "6"
}, {
    "id": "US.PA",
    "name": "Pennsylvania",
    "value": "3"
}, {
    "id": "US.AL",
    "name": "Alabama",
    "value": "3"
}, {
    "id": "US.KS",
    "name": "Kansas",
    "value": "3"
}, {
    "id": "US.NV",
    "name": "Nevada",
    "value": "6"
}, {
    "id": "US.OK",
    "name": "Oklahoma",
    "value": "2"
}, {
    "id": "US.NE",
    "name": "Nebraska",
    "value": "2"
}, {
    "id": "US.KY",
    "name": "Kentucky",
    "value": "2"
}, {
    "id": "US.WA",
    "name": "Washington",
    "value": "6"
}, {
    "id": "US.OR",
    "name": "Oregon",
    "value": "6"
}, {
    "id": "US.LA",
    "name": "Louisiana",
    "value": "1"
}, {
    "id": "US.SD",
    "name": "South Dakota",
    "value": "1"
}, {
    "id": "US.SC",
    "name": "South Carolina",
    "value": "1"
}, {
    "id": "US.OH",
    "name": "Ohio",
    "value": "1"
}, {
    "id": "US.ND",
    "name": "North Dakota",
    "value": "1"
}, {
    "id": "US.NC",
    "name": "North Carolina",
    "value": "1"
}, {
    "id": "US.TX",
    "name": "Texas",
    "value": "1"
}, {
    "id": "US.CO",
    "name": "Colorado",
    "value": "1"
}, {
    "id": "US.WY",
    "name": "Wyoming",
    "value": "1"
}, {
    "id": "US.TN",
    "name": "Tennessee",
    "value": "1"
}, {
    "id": "US.RI",
    "name": "Rhode Island",
    "value": "0"
}, {
    "id": "US.AK",
    "name": "Alaska",
    "value": "0"
}, {
    "id": "US.MO",
    "name": "Missouri",
    "value": "0"
}, {
    "id": "US.NM",
    "name": "New Mexico",
    "value": "0"
}, {
    "id": "US.MS",
    "name": "Mississippi",
    "value": "0"
}, {
    "id": "US.MN",
    "name": "Minnesota",
    "value": "0"
}, {
    "id": "US.MI",
    "name": "Michigan",
    "value": "0"
}, {
    "id": "US.MA",
    "name": "Massachusetts",
    "value": "0"
}, {
    "id": "US.MD",
    "name": "Maryland",
    "value": "0"
}, {
    "id": "US.IA",
    "name": "Iowa",
    "value": "0"
}, {
    "id": "US.IN",
    "name": "Indiana",
    "value": "0"
}, {
    "id": "US.NH",
    "name": "New Hampshire",
    "value": "0"
}, {
    "id": "US.IL",
    "name": "Illinois",
    "value": "0"
}, {
    "id": "US.ID",
    "name": "Idaho",
    "value": "6"
}, {
    "id": "US.HI",
    "name": "Hawaii",
    "value": "0"
}, {
    "id": "US.DE",
    "name": "Delaware",
    "value": "0"
}, {
    "id": "US.UT",
    "name": "Utah",
    "value": "6"
}, {
    "id": "US.VT",
    "name": "Vermont",
    "value": "0"
}, {
    "id": "US.VA",
    "name": "Virginia",
    "value": "0"
}, {
    "id": "US.CT",
    "name": "Connecticut",
    "value": "0"
}, {
    "id": "US.WV",
    "name": "West Virginia",
    "value": "0"
}, {
    "id": "US.WI",
    "name": "Wisconsin",
    "value": "0"
}, {
    "id": "US.MT",
    "name": "Montana",
    "value": "6"
}]